name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tzdata \
          build-essential \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          wget \
          pkg-config \
          git \
          cryptsetup \
          fakeroot

    - name: Install Go
      run: |
        wget https://golang.org/dl/go1.20.3.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.20.3.linux-amd64.tar.gz
        echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

    - name: Install Singularity
      run: |
        echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
        export VERSION=3.9.9 # use this version
        wget https://github.com/sylabs/singularity/releases/download/v$VERSION/singularity-ce-$VERSION.tar.gz
        tar -xzf singularity-ce-$VERSION.tar.gz
        cd singularity-ce-$VERSION
        ./mconfig
        make -C builddir
        sudo make -C builddir install
        singularity version

    - name: Initialize and update submodules
      run: git submodule update --init --recursive

    - name: Build Singularity image
      run: |
        export SINGULARITY_CACHEDIR=$HOME/.singularity/cache
        mkdir -p $SINGULARITY_CACHEDIR
        singularity build --fakeroot matrix_mult.sif Singularity

    - name: Upload Singularity image
      uses: actions/upload-artifact@v2
      with:
        name: matrix_mult.sif
        path: matrix_mult.sif

    - name: Run tests in Singularity container
      run: |
        source $GITHUB_ENV
        sudo singularity exec --fakeroot matrix_mult.sif /opt/matrix_mult/build/MatrixMultiplication
        sudo singularity exec --fakeroot matrix_mult.sif ctest --test-dir /opt/matrix_mult/build
