name: Remote Build Singularity Container

on:
  push:
    branches:
      - feature_singularity_container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Singularity
      run: |
        sudo apt-get update
        sudo apt-get install -y singularity-container

    - name: Remote Build Singularity image
      run: |
        singularity remote login --tokenfile ${{ secrets.SINGULARITY_TOKEN }}
        singularity build --remote matrix_mult.sif Singularity.def

    - name: Upload Singularity image to repository
      run: |
        singularity push matrix_mult.sif library://yanlong/REPO/matrix_mult:1.0.0
      env:
        SYLABS_TOKEN: ${{ secrets.SINGULARITY_TOKEN }}
