name: C++ CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Singularity
      run: |
        sudo apt-get update
        sudo apt-get install -y singularity-container
    - name: Initialize and update submodules
      run: git submodule update --init --recursive
    - name: Build Singularity container
      run: |
        sudo singularity build matrix_mult.sif Singularity
    - name: Run Tests inside Singularity container
      run: |
        sudo singularity exec matrix_mult.sif ctest --test-dir /opt/matrix_mult/build